name: dispatch downstream

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
    dispatch_maafw:
        runs-on: ubuntu-latest
        steps:
          - name: Trigger MaaFramework
            uses: peter-evans/repository-dispatch@v4
            with:
                token: ${{ secrets.MAAFRAMEWORKTRIGGER }}
                repository: MaaXYZ/MaaFramework
                event-type: MaaUtilsUpdated


