name: dispatch downstream

on:
  push:
    branches:
      - "master"

jobs:
    dispatch_maafw:
        runs-on: ubuntu-latest
        steps:
          - name: Trigger B Repository Build
            uses: peter-evans/repository-dispatch@v4
            with:
                token: ${{ secrets.GITHUB_TOKEN }}
                repository: MaaXYZ/MaaFramework
                event-type: MaaUtilsUpdated
